services:
  app:
    build: .
    depends_on:
      - db
    environment:
      ENV: ${ENV:-prod}
      DB_HOST: ${DB_HOST:-db}
      DB_NAME: ${DB_NAME:-encurtago}
      DB_USER: ${DB_USER:-encurtago}
      DB_PASSWORD: ${DB_PASSWORD-encurtago}
    ports:
      - "8080:8080"
    networks:
      - postgres
    restart: unless-stopped
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER:-encurtago}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-encurtago}
      POSTGRES_DB: ${DB_NAME:-encurtago}
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
networks:
  postgres:
    driver: bridge
